### ISSUE TITLE
Migrate to WASDK

### ISSUE THREAD

**Issue by Lamparter** [RiversideValley/Emerald#14]
### ⏱️ Before you start...

- [X] I have checked whether a similar feature request has already been reported.

### 📄 Description

The app currently uses the Universal Windows Platform. However, it seems like the UWP will be deprecated at some point in time. So, better to migrate to the WASDK now while SeaDev still in beta stage.
@NoobNotFound / @developerx-official here's a helpful guide: https://docs.microsoft.com/en-us/windows/apps/get-started/migrate-from-uwp-to-winappsdk

**Comment by NoobNotFound** [comment]
yeah. I was thinking about that. I tried once using that assistant but have to change many namescapes and the titlebar went shit so I gave up. want to try again.
