### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by Lamparter** [RiversideValley/Emerald#15]
### ⏱️ Before you start...

- [x] I have checked whether a similar feature request has already been reported.

### 📄 Description

There are many problems about the current UI.
Here are some:
Unintuitive placement of buttons
Incorrect use of controls
Some areas not abiding to the Fluent Design Language (background should be mica, etc.)

### 📸 Assets

Here are some concepts from other projects that may spark inspiration:
![image](https://user-images.githubusercontent.com/71598437/188210939-767fbb97-01af-4759-bdd7-cb0772f7ea60.png)
This one could be improved and is very old but it is very intuitive and natural in where you'd expect buttons to go.
![image](https://user-images.githubusercontent.com/71598437/188210955-261d8d8a-5309-4a66-b10f-86a2b019766c.png)

**Comment by NoobNotFound** [comment]
nice!. I'm kinda big noob in UI designs

**Comment by NoobNotFound** [comment]
we need to start this

**Comment by DeveloperWOW64** [comment]
> we need to start this

OK. I need to be able to *actually run* the app first, just wait...
