### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by Lamparter** [RiversideValley/Emerald#17]
There are many ideas I have and problems to report about SeaDev and its branding:
- [x] a) The full SDLauncher is honestly just the worst name ever. Don't include the name 'launcher' as it doesn't assert a certain *personality* to the brand. Just 'SeaDev' is simplified and better.
- [x] b) What is the point of the word SeaDev? @NoobNotFound? What is its definition? Also, 'Dev' can't be part of the real product name as it implies that SeaDev is not perfect/not developed enough/unstable etc. 
There are certainly better names. SeaDev is the start of an amazing brand but the name doesn't quite have that *ring* to it. Personally, Emerald - obviously a spin-off the original name - would be better. It's short and simple, related to the app, and it's original.
- [x] c) The website is someone having a good idea but not executing it properly, which pretty much sums up all of SeaDev's branding.
- [x] d) Why have two repositories? SDLauncher-UWP and SDLauncher seem to be the exact same, which is somewhat confusing. Moreover, using the name 'UWP' isn't good for branding.

**Comment by DeveloperWOW64** [comment]
- [ ] e) The current logo is not fluent. We need a better logo and also, the current one looks like a knock-off to an outsider.

**Comment by NoobNotFound** [comment]
> * [ ]  a) The full SDLauncher is honestly just the worst name ever. Don't include the name 'launcher' as it doesn't assert a certain _personality_ to the brand. Just 'SeaDev' is simplified and better.
> * [ ]  b) What is the point of the word SeaDev? @NoobNotFound? What is its definition? Also, 'Dev' can't be part of the real product name as it implies that SeaDev is not perfect/not developed enough/unstable etc.
>   There are certainly better names. SeaDev is the start of an amazing brand but the name doesn't quite have that _ring_ to it. Personally, Emerald - obviously a spin-off the original name - would be better. It's short and simple, related to the app, and it's original.

Well, the name of the team or the name of the launcher were not made by me, all of them were made by @TurtlzYT .
And yes of course, I want a better name. BTW the previous name of the launcher is `Emerald Launcher`.

**Comment by DeveloperWOW64** [comment]
> BTW the previous name of the launcher is `Emerald Launcher`.

Yep. that's exactly why I recommend the name Emerald. Emerald shows class, makes you think of a nice UI, makes you think of Minecraft due to its obvious relation, and overall is unique.

**Comment by NoobNotFound** [comment]
> * [ ]  c) The website is someone having a good idea but not executing it properly, which pretty much sums up all of SeaDev's branding.

Yeah but I even don't know HTML things very much it was built using the nicepage
.
.
.
So we need web designers

**Comment by DeveloperWOW64** [comment]
> So we need web designers

I exist, BTW.

**Comment by DeveloperWOW64** [comment]
I'm a web dev.

**Comment by NoobNotFound** [comment]
> * [ ]  d) Why have two repositories? SDLauncher-UWP and SDLauncher seem to be the exact same, which is somewhat confusing. Moreover, using the name 'UWP' isn't good for branding.

cuase it's easier to handle optifine files and yeah it's not a good idea

**Comment by NoobNotFound** [comment]
> I'm a web dev.
Wow Nnce!

**Comment by NoobNotFound** [comment]
> * [ ]  e) The current logo is not fluent. We need a better logo and also, the current one looks like a knock-off to an outsider.

The fact is we don't even have graphic designers and I don't want to hire them.

**Comment by DeveloperWOW64** [comment]
> The fact is we don't even have graphic designers and I don't want to hire them.

@josephbeattie SeaDev (name yet to be changed) is an open-source Fluent Minecraft client and we need a logo. Not to overburden you, but I'd love it if you could do something for us.

**Comment by DeveloperWOW64** [comment]
> @josephbeattie SeaDev (name yet to be changed) is an open-source Fluent Minecraft client and we need a logo. Not to overburden you, but I'd love it if you could do something for us.

We're looking for an icon like an emerald from minecraft but made fluent, if that helps.

> ![image](https://user-images.githubusercontent.com/71598437/189475418-ab567202-0eaa-4657-881c-9fbeef5d86b4.png)
> just like this but fluent, if you could.

**Comment by DeveloperWOW64** [comment]
I suppose we should also add AZP.

**Comment by DeveloperWOW64** [comment]
And CodeFactor, perhaps.

**Comment by DeveloperWOW64** [comment]
[ ] - f) We need a codename. I used 'gem' inside the protocol, so I think that should be our codename. @NoobNotFound Do you have any other ideas?

**Comment by NoobNotFound** [comment]
can't we make codename also as emerald

**Comment by DeveloperWOW64** [comment]
> can't we make codename also as emerald

a codename is never the same as the name. Otherwise, it wouldn't be a codename lol 
![image](https://user-images.githubusercontent.com/71598437/189690136-c7f0be8f-86f3-4bea-bfc7-1d016cf91614.png)
