### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by BobbyESP** [RiversideValley/Emerald#34]
Hi guys! I'm interested in helping to the project and I just wated to ask If I need to follow any steps before starting to contribute!

I tried to run the Emerald project but it asks me for an Azure MSAL client id, thanks!

**Comment by Lamparter** [comment]
Hi @BobbyESP!
Nice to hear that you want to contribute (me and @NoobNotFound have been lacking time to do so)
I will add you to the org immediately. You should also join our Discord server https://discord.com/invite/Z74UAQ5vPR and we can discuss matters further. Thanks!
